R/snapshot.R, tests/testthat/recorded_tests/inline-img-src/app.R, tests/testthat/recorded_tests/inline-img-src/tests/mytest-expected/001.json, tests/testthat/recorded_tests/inline-img-src/tests/mytest.R
=> Fix image data detection

docs/articles/shinytest.html
=> fix typo in shinytest getting started docs

inst/recorder/app.R
=> Escape the escape character

inst/recorder/app.R, inst/recorder/recorder.js, inst/recorder/www/inject-recorder.js
Adds the ability to take a snapshot by pressing Ctrl-Shift-S (#240)
=> Generate a snapshot by pressing shift-S, closes #240

R/install.R, man/dependenciesInstalled.Rd, vignettes/shinytest.Rmd
Thanks for the package! I was reading the docs to debug an issue I was experiencing and noticed a couple of misspellings, so I thought I'd just fix them here.
=> Fix a few spellings

DESCRIPTION, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/001.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/002.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/003.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/004.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/005.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/mytest-expected/006.json, tests/testthat/recorded_tests/rmd-prerendered/tests/mytest-expected/001.json, tests/testthat/recorded_tests/rmd-prerendered/tests/mytest-expected/002.json, tests/testthat/recorded_tests/rmd/tests/mytest-expected/001.json, tests/testthat/recorded_tests/rmd/tests/mytest-expected/002.json, tests/testthat/test-list-widgets.R, tests/testthat/test-recorded-tests.R
* Removes `-selectized` input values fixed in https://github.com/rstudio/shiny/issues/2396
=> Bump shiny version to >= 1.3.2 and update tests

inst/recorder/app.R
Closes #302.
@jhk0530 Can you try installing this branch and see if it fixes your problem?
=> Use HTML-escaped cmd character

NEWS.md, R/snapshot.R
Closes https://github.com/rstudio/shinytest/issues/131
=> Always display message about how to view diff

DESCRIPTION, R/snapshot.R, R/utils.R
=> Store non utf-8 characters properly in json files

R/snapshot.R
=> Improve missing snapshots message

R/shiny-driver.R, man/ShinyDriver.Rd
=> Add setInputs to ShinyDriver usage

R/shiny-driver.R, man/ShinyDriver.Rd
So that all ShinyDriver mutation methods return self invisibly
Fixes #264
=> Add missing returns

NEWS.md, R/shiny-driver.R, man/ShinyDriver.Rd, tests/testthat/test-shiny-driver.R
=> Implement ShinyDriver$waitForShiny()

NEWS.md, R/widget.R, man/Widget.Rd, tests/testthat/apps/click-me/app.R, tests/testthat/test-widget.R
=> Add click method to widget

R/test-app.R
Reverts change made in bd9646a
=> Have testApp() load shinytest (so test scripts don't have to)

NEWS.md, R/initialize.R, R/shiny-driver.R, man/ShinyDriver.Rd
Will come in handy for https://github.com/rstudio/shinycoreci-apps/pull/73
=> Add options argument to ShinyDriver() (for setting options in child process)

DESCRIPTION, NEWS.md
=> 1.5.0 release candidate

NEWS.md, inst/htmlwidgets/diffviewer.js
This PR addresses https://github.com/r-lib/diffviewer/issues/9, which also is an issue for this package.
=> Don't ignore any pixel differences

R/phantom.R, man/installDependencies.Rd, tests/testthat/test-save-app.R, tests/testthat/test-shiny-driver.R
=> Restructure docs to expose `installDependencies()`

.github/workflows/pkgdown.yaml, _pkgdown.yml
=> Verify that there are missing pkgdown entries

.github/workflows/pkgdown.yaml
=> Do not deploy pkgdown except for push event
