inst/js/shiny-tracer.js
This PR doesn't change any functionality, but it does set the stage for more complex JS code that I would like to add. The closure lets you simulate private variables and functions -- only the members on the `shinytest` object are "public".
This pattern is used by Vega, and I've used it in other code of mine:
https://github.com/vega/vega/blob/master/src/scene/axis.js
If you don't like it, feel free to let me know. :)
Also, I changed all the tabs to spaces. I hope that's OK. My editor doesn't really like mixing tabs and spaces.
=> Refactor shiny-tracer.js

R/app.R, R/set-inputs.R, inst/js/shiny-tracer.js
This is an initial attempt at setting inputs in one go. It shifts more of the work into Javascript.
Here's how it can be used:
```R
app <- shinyapp$new("tests/testthat/apps/081-widgets-gallery")
expect_update(app, checkbox = FALSE, output = "checkboxOut")
expect_equal(app$get_value("checkboxOut"), "[1] FALSE")
app$set_inputs(checkbox = TRUE, text = "Hello, world!")
expect_equal(app$get_value("checkbox"), TRUE)
expect_equal(app$get_value("text"), "Hello, world!")
```
A few notes:
* It's not possible to set a single value right now, because of the unboxing behavior. 
* Setting the checkbox to FALSE doesn't work yet.
* It doesn't check the type of the input right now -- it just sends names and values to the Javascript side, and then that side sets the values all at once. This means that …
=> Add shinyapp$set_inputs()

R/initialize.R
This is needed when the tests run during R CMD check.
=> Set .libPaths() in child R process

R/assertions.R
Here's a set of tests:
```R
library(testthat)
expect_true(is_all_named(NULL))
expect_true(is_all_named(c()))
expect_false(is_all_named(c(1)))
expect_true(is_all_named(c(a=1)))
expect_false(is_all_named(c(a=1, 2)))
expect_false(is_all_named(c(a=1, 2)[2]))  # Vector has name attribute, but all names are ""
```
On master, the first two tests fail. After the fix, all tests pass.
I saw this when I ran into the same issue in webdriver. The current implementation is actually different there! I'll submit a fix there as well.
=> Fix is_all_named for zero-length vectors

R/widget.R
This goes with MangoTheCat/webdriver#44.
The interface makes it feel like the method is being called on the element, but really what happens is that the request is made on the session, with the widget's DOM ID as the CSS selector.
This works now:
```R
app <- shinyapp$new("tests/testthat/apps/081-widgets-gallery")
app$find_widget("file")$upload_file("DESCRIPTION")
Sys.sleep(0.5)
app$get_value("fileOut")
```
I used an ugly hack to get the `session` object to make the request. @gaborcsardi, can you think of a better way to do this?
=> Add widget$upload_file()

.Rbuildignore, .travis.yml, DESCRIPTION, R/app-get-all-values.R, R/app.R, R/debugging.R, R/set-inputs.R, appveyor.yml, inst/js/shiny-tracer.js, man/shinyapp.Rd, tests/testthat.R, tests/testthat/test-app-set-inputs.R
This is a WIP. It modifies `app$set_inputs()` so that it returns all input, output, and error values. (Error values are any outputs which have errored on the server.)
This makes it possible to do things like:
```R
app <- shinyapp$new("tests/testthat/apps/081-widgets-gallery")
res <- app$set_inputs(checkbox = FALSE, text = "Hello, world!")
expect_identical(res$outputs$checkboxOut, "[1] FALSE")
expect_identical(res$outputs$textOut, "[1] \"Hello, world!\"")
```
Some details: The default behavior is for the client to send values to the server, then wait for the server to send back a response with new output values, and only then fetch all the values. The waiting is event-driven, instead of polled, so it should be fast. If the server doesn't send back a response before a specified timeout …
=> Change set_inputs() to return output values

R/shiny-driver.R, R/snapshot.R, inst/recorder/app.R, inst/recorder/recorder.js, inst/recorder/www/inject-recorder.js
This closes #72.
It also requires rstudio/shiny#1559 to be merged so that `recordTest` can record download events. That PR also makes it so shinytest doesn't record the value of a `downloadHandler`, because it changes each time an app is run.
=> Add support for testing file downloads

R/recorder.R, inst/recorder/app.R, man/recordTest.Rd
We want the recorder to be able to generate a script that can be used for load testing. This initial PR does a few things:
- It allows recordTest to be called with an argument, load_test
- If load_test is True, an option is set that the recorder app can pick up
- If load_test is True, the default behavior of the recorder is changed in a few places
=> initial changes to the recorder for load test

R/initialize.R, tests/testthat/test-shiny-driver.R
Fixed a minor error in ```sd_startShiny``` that caused ```recordTest``` to not be able to run, with the latest version of processx at least, exiting with the following error:
```Error in readLines(process_get_error_connection(self, private), ...) : 
'con' is not a connection```
Added stderr = "|" argument to ```process$new``` to get around this.
=> read_error_lines does not work with latest version of processx unless you pass | for stderr

inst/diffviewerapp/app.R
Running `shinytest::viewTestDiff("~/RStudio/sparklyr/shinytest", "mytest")` triggers:
```
Differences in current results found for: mytest
Viewing diff for mytest
Loading required package: shiny
Error in viewTestDiffWidget(app_dir, test_name) : 
could not find function "viewTestDiffWidget"
```
We are just missing to import `shinytest` in the Shiny app.
=> Allow viewing diff even when shinytest is not imported

inst/recorder/www/recorder.css
Would you be open to tweaking the iframe border color and make it visible only on the right side? I think it looks better:
=> Tweak recorder iframe borders

vignettes/package.Rmd
_shinytest_ 1.3.0 is on CRAN now, the remark about the `Remotes:` section no longer fits the scope.
=> On CRAN now

DESCRIPTION, R/recorder.R, inst/recorder/app.R, inst/recorder/www/inject-recorder.js
Right now, Shinytest does not work with RStudio Server 1.2 (https://github.com/rstudio/rstudio/issues/4054). This is because it relies on RStudio Server's open port proxying system (i.e. the `/p/1234` URL for connecting to port 1234), which has been removed in RStudio 1.2.
The fix is to remove the JavaScript URL rewriting scheme, and to rewrite the URL ahead of time instead. The development version of the RStudio API has a method for safely generating port proxy URLs; this is used if it's available. If not, we are presumably using RStudio 1.1, and use largely the same regex we did before to reshape the URL in server mode.
=> Translate localhost URLs using rstudioapi if available

DESCRIPTION, NEWS.md, R/set-inputs.R, R/shiny-driver.R, docs/articles/faq.html, docs/articles/in-depth.html, docs/articles/index.html, inst/js/shiny-tracer.js, inst/recorder/app.R, man/ShinyDriver.Rd, vignettes/in-depth.Rmd
This PR adds the ability to record and play back inputs for which there is not an input binding, as is the case with htmlwidgets that have inputs, like DT and plotly.
When playing back, the input value will be set so that the R Shiny process knows about it, but the corresponding object in the browser will not -- so, for example, in the app below, if a row in the DT is selected during the recording phase, it will not be highlighted during playback. For some applications, this is OK, for others it is not.
Example test app with DT:
```R
library(shiny)
ui <- fluidPage(
numericInput("num", "number", 5),
DT::dataTableOutput("table"),
verbatimTextOutput("info")
)
server <- function(input, output, session) {
output$table <- DT::renderDataTable({
head(iris, input$num)
})
output$info <- …
```
=> Allow recording/playing back inputs that do not have a binding

R/set-inputs.R, R/shiny-driver.R, inst/js/shiny-tracer.js, inst/recorder/app.R, inst/recorder/recorder.js, inst/recorder/www/inject-recorder.js
This PR adds the support for the priority argument of `Shiny.setInputValue()`, which addresses #239
=> Record inputs with no binding and event priority

DESCRIPTION, NEWS.md, R/test-app.R, tests/testthat/apps/050-kmeans-example/.gitignore, tests/testthat/example_test_dirs/empty-nested/tests/st.R, tests/testthat/example_test_dirs/mixed-toplevel/tests/testa.r, tests/testthat/example_test_dirs/mixed-toplevel/tests/testb.R, tests/testthat/example_test_dirs/nested/tests/shinytests/st.R, tests/testthat/example_test_dirs/nested/tests/shinytests/whatever.R, tests/testthat/example_test_dirs/simple/tests/testa.r, tests/testthat/example_test_dirs/simple/tests/testb.R, tests/testthat/test-find-tests.R
(Probably best to review each commit separately)
This PR encourages users to start storing tests in `tests/shinytests/` instead of at the top-level of `tests/`. The old model is still supported (though we now require that every R file in `tests/*.R` include the magic string `app <- ShinyDriver$new(` as the flag to us that it's a shinytest.
More specifically, the algorithm is:
1. Check to see if `tests/shinytests/` exists. If so, use it.
2. Check to see if all the top-level R files in `tests/` appear to be shinytests. If
some are and some aren't, throw an error.
3. Assuming all top-level R files in `tests/` appear to be shinytests (because they include the magic string), return that dir.
Run an app that had existing shinytests (e.g. see the `tests/testthat/recorded_tests/009-upload/` app …
=> Recommend storing tests in tests/shinytests/*.R

R/test-app.R, tests/testthat/test-find-tests.R
Before using the tests/shinytests directory because it exists, do a quick check to see if any of the files in the top-level appear to be shinytests. If so warn, as this might be a mistake.
Based on a suggestion from @shalutiwari when she was reviewing the previous work.
Starting with an app that has working shinytests in the top-level `tests/` directory, create a new `tests/shinytests` directory then run the tests again. You should see that we use the (empty) `tests/shinytests` directory, and warn that there are files in the top-level that appear to be shinytests. 
If you copy those working tests into `tests/shinytests`, you should see them running and working, but continue to get the error about shinytests in the top-level.
If you delete the shinytests from the top-level `tests/` …
=> Check for top-level tests

R/recorder.R, R/test-app.R
Was incompletely reversed when I went from doMessage to !quiet in 723703ad
Now behaves as follows for an app with no `tests/shinytests/` dir:
```
> testApp("~/Temp/shinytestapp/myapp/")
shinytests should be placed in the tests/shinytests directory. Storing them in the top-level tests/ directory will be deprecated in the future.
Running mytest.R
==== Comparing mytest... No changes.
```
And for an app that has spurious shinytest files in the top level but also has a tests/shinytests:
```
> testApp("~/Temp/shinytestapp/myapp/")
Running mytest.R
==== Comparing mytest...
No existing snapshots at mytest-expected/. This is a first run of tests.
Updating baseline results at ~/Temp/shinytestapp/myapp//tests/shinytests/mytest-expected...
Renaming …
```
=> Invert quiet logic

R/test-app.R, tests/testthat/example_test_dirs/empty-toplevel/tests/file.R, tests/testthat/test-find-tests.R
Also add tests to confirm that we prefer nested for !mustExist, but error if we find a messy top-level with no nested dir in mustExist.
Should resolve two reported bugs:
> @jeff Third issue is when I am recording the app with empty tests directory then its creating mytest.R and mytest-expected in tests directory. Why its not creating the correct directory structure then? It should create shinytests directory under tests directory and keep these files in there.
and
> @jeff First issue where only shinytest.R file is there in shinytests (Jeff Note: I think she meant the `tests/` directory based on the output shown below) directory and I am trying to get a new recording. Then recordTest errors out. Expected behavior should be that it should let you create mytest.R file.
```
shalus-MBP:tests …
```
=> Use nested dir if !mustExist and empty top-level

R/test-app.R, tests/testthat/test-find-tests.R
This is the current behavior in the RStudio IDE. I believe they must go one directory up from wherever the test got recorded to compute the appdir. Unfortunately, that calculation is no longer correct so we need to make a special case for this.
Closes #293
=> Support being given an appdir that is actually the `tests/` dir

NEWS.md, R/session.R, R/utils.R, inst/diffviewerapp/app.R
Previously, on Windows, the reported resolution of screenshots depended on the actual screen resolution. For example, on one Windows machine, it might report a screenshot to be 96 ppi, while on another machine, it might report it to be 240 ppi, even though the image data is exactly the same from the two machines. This caused problems when expected results were generated on one machine and the tests were run on another machine. Now, the screenshots are modified so that they always report 72 ppi resolution, which is the same as on Mac and Linux.
See https://github.com/ariya/phantomjs/issues/10659#issuecomment-14993827 for more about the issue.
=> Normalize reported resolution in PNG header

R/shiny-driver.R
Followup to #304 
Most likely there will be plots in `output`.  These can be very costly when returning many plots and only needing one of the input values.
=> Do not retrieve all iotypes within app$waitForValue

vignettes/ci.Rmd
This isn't currently on the RStudio Connect roadmap, probably best not to mention here.
Is there anything else I need to do to render to HTML version? Or is that auto-built on deploy?
=> Remove RStudio Connect Reference

NEWS.md, R/snapshot.R, R/utils.R
It turns out that the change in #318 added an extra `\n` to JSON output. This PR changes it so that it doesn't add an extra newline, and renames the function to `write_utf8`, so that it's consistent with `read_utf8` in this package.
=> Change writeUTF8 so it doesn't add extra newline

R/set-inputs.R, R/utils.R
Works like inform() but also tells you where the message came from. Fixes #127.
I have zero clues about how to test it, but this gives you an idea of what the output will look like:
```R
f <- function() g()
g <- function() h()
h <- function() inform_where("Bad things happened")
#> Bad things happened
#>     █
#>  1. └─global::f()
#>  2.   └─global::g() ~/Desktop/test.R:2:5
#>  3.     └─global::h() ~/Desktop/test.R:3:5
```
=> Implement inform_where()

R/utils.R, tests/testthat/test-utils.R
Offending line: https://github.com/rstudio/shinytest/commit/bd9646ae6fa770f139add3144391f04fc39177dc#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0cR128
Causing errors in shiny template tests.
?file.exists
> (However, directory names must not include a trailing backslash or slash on Windows.)
=> `app_path()` should work with trailing `/`

DESCRIPTION, R/utils.R, tests/testthat/apps/user-error/app.R, tests/testthat/recorded_tests/041-dynamic-ui/tests/shinytest/mytest-expected/001.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/shinytest/mytest-expected/002.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/shinytest/mytest-expected/005.json, tests/testthat/recorded_tests/041-dynamic-ui/tests/shinytest/mytest-expected/006.json, tests/testthat/recorded_tests/app-waitForValue/tests/shinytest/mytest-expected/001.json, tests/testthat/recorded_tests/app-waitForValue/tests/shinytest/mytest-expected/002.json, tests/testthat/recorded_tests/inline-img-src/tests/shinytest/mytest-expected/001.json, tests/testthat/test-utils.R
(Builds on https://github.com/rstudio/shiny/pull/3229)
Due to [recent changes](https://github.com/rstudio/shinytest/commit/bd9646ae6fa770f139add3144391f04fc39177dc), running `testApp()` on a directory with a `app.R`/`server.R` file (which throws an error) now throws with an incorrect, and very confusing, error:
```r
> shinytest::testApp()
Error: `appDir` doesn't contain 'app.R', 'server.R', or exactly one '.Rmd'
```
For example, suppose I have a `./app.R` file that simply contains:
```r
stop("boom")
```
With this fix, you'll now get the same error that you'd get if you were to do `shiny::runApp()`
```r
> shinytest::testApp()
Error in value[[3L]](cond) : boom
```
=> Leverage shinyAppDir()'s new exception class for more accurate error messages

DESCRIPTION, NEWS.md, R/initialize.R
This fixes a problem with using phantomjs 2.5.0-beta on Windows:
```
Error in session_makeRequest(self, private, endpoint, data, params, headers): Detected a page unload event; asynchronous script execution does not work across page loads.
```
This PR makes `$initialize()` to wait until the browser actually navigates to the page before continuing.
=> In `initialize()`, wait for navigation

vignettes/package.Rmd
should make it easier to use interactively
spun out from other changes in https://github.com/rstudio/shinytest/pull/396, before it gets bogged down there in other changes
=> use test_path for app paths

vignettes/package.Rmd
related to, though not fixing https://github.com/rstudio/shinytest/issues/397
As suggested by @schloerke in #398:
> I would rather we mention to reinstall where appropriate, rather than using `devtools::load_all()`.
=> Remind users to install the package

DESCRIPTION
This change is meant to address a message from BDR:
> CRAN packages referring to 'Mango Solutiond'
>
> That is
> 
>         mangoTraining pak processx remotes sasMap shinytest
> 
> 'Mango Solutions' as a software company appears no longer to exist: it
> may mow be part of 'Ascent Digital Science'.  As the manual says [cph]
> refers to
> 
> "(copyright holder, which should be the legal name for an institution or
> corporate body)"
> 
> and needs to be identifiable to people wiching to ask for copyright
> permissions.
> 
> And where they are not the only named copyright holder it needs to be
> made clear which parts are owned by which copyright holder.
> 
> Likely RStudio as copyright holder needs to be updated.
=> Update authors in DESCRIPTION
